/*
Okta Management APIs

Allows customers to easily access the Okta API

Copyright 2018 - Present Okta, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

API version: 3.0.0
Contact: devex-public@okta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package okta

import (
	"encoding/json"
)

// SignInPage struct for SignInPage
type SignInPage struct {
	PageContent string `json:"pageContent"`
	Type string `json:"type"`
	Url *string `json:"url,omitempty"`
	WidgetCustomizations *SignInPageAllOfWidgetCustomizations `json:"widgetCustomizations,omitempty"`
	// The version specified as a [Semantic Version](https://semver.org/).
	WidgetVersion *string `json:"widgetVersion,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SignInPage SignInPage

// NewSignInPage instantiates a new SignInPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignInPage(pageContent string, type_ string) *SignInPage {
	this := SignInPage{}
	this.PageContent = pageContent
	this.Type = type_
	return &this
}

// NewSignInPageWithDefaults instantiates a new SignInPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignInPageWithDefaults() *SignInPage {
	this := SignInPage{}
	return &this
}

// GetPageContent returns the PageContent field value
func (o *SignInPage) GetPageContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PageContent
}

// GetPageContentOk returns a tuple with the PageContent field value
// and a boolean to check if the value has been set.
func (o *SignInPage) GetPageContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageContent, true
}

// SetPageContent sets field value
func (o *SignInPage) SetPageContent(v string) {
	o.PageContent = v
}

// GetType returns the Type field value
func (o *SignInPage) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SignInPage) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SignInPage) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SignInPage) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInPage) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SignInPage) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SignInPage) SetUrl(v string) {
	o.Url = &v
}

// GetWidgetCustomizations returns the WidgetCustomizations field value if set, zero value otherwise.
func (o *SignInPage) GetWidgetCustomizations() SignInPageAllOfWidgetCustomizations {
	if o == nil || o.WidgetCustomizations == nil {
		var ret SignInPageAllOfWidgetCustomizations
		return ret
	}
	return *o.WidgetCustomizations
}

// GetWidgetCustomizationsOk returns a tuple with the WidgetCustomizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInPage) GetWidgetCustomizationsOk() (*SignInPageAllOfWidgetCustomizations, bool) {
	if o == nil || o.WidgetCustomizations == nil {
		return nil, false
	}
	return o.WidgetCustomizations, true
}

// HasWidgetCustomizations returns a boolean if a field has been set.
func (o *SignInPage) HasWidgetCustomizations() bool {
	if o != nil && o.WidgetCustomizations != nil {
		return true
	}

	return false
}

// SetWidgetCustomizations gets a reference to the given SignInPageAllOfWidgetCustomizations and assigns it to the WidgetCustomizations field.
func (o *SignInPage) SetWidgetCustomizations(v SignInPageAllOfWidgetCustomizations) {
	o.WidgetCustomizations = &v
}

// GetWidgetVersion returns the WidgetVersion field value if set, zero value otherwise.
func (o *SignInPage) GetWidgetVersion() string {
	if o == nil || o.WidgetVersion == nil {
		var ret string
		return ret
	}
	return *o.WidgetVersion
}

// GetWidgetVersionOk returns a tuple with the WidgetVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInPage) GetWidgetVersionOk() (*string, bool) {
	if o == nil || o.WidgetVersion == nil {
		return nil, false
	}
	return o.WidgetVersion, true
}

// HasWidgetVersion returns a boolean if a field has been set.
func (o *SignInPage) HasWidgetVersion() bool {
	if o != nil && o.WidgetVersion != nil {
		return true
	}

	return false
}

// SetWidgetVersion gets a reference to the given string and assigns it to the WidgetVersion field.
func (o *SignInPage) SetWidgetVersion(v string) {
	o.WidgetVersion = &v
}

func (o SignInPage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pageContent"] = o.PageContent
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.WidgetCustomizations != nil {
		toSerialize["widgetCustomizations"] = o.WidgetCustomizations
	}
	if o.WidgetVersion != nil {
		toSerialize["widgetVersion"] = o.WidgetVersion
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *SignInPage) UnmarshalJSON(bytes []byte) (err error) {
	varSignInPage := _SignInPage{}

	err = json.Unmarshal(bytes, &varSignInPage)
	if err == nil {
		*o = SignInPage(varSignInPage)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &additionalProperties)
	if err == nil {
		delete(additionalProperties, "pageContent")
		delete(additionalProperties, "type")
		delete(additionalProperties, "url")
		delete(additionalProperties, "widgetCustomizations")
		delete(additionalProperties, "widgetVersion")
		o.AdditionalProperties = additionalProperties
	} else {
		return err
	}

	return err
}

type NullableSignInPage struct {
	value *SignInPage
	isSet bool
}

func (v NullableSignInPage) Get() *SignInPage {
	return v.value
}

func (v *NullableSignInPage) Set(val *SignInPage) {
	v.value = val
	v.isSet = true
}

func (v NullableSignInPage) IsSet() bool {
	return v.isSet
}

func (v *NullableSignInPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignInPage(val *SignInPage) *NullableSignInPage {
	return &NullableSignInPage{value: val, isSet: true}
}

func (v NullableSignInPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignInPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

