/*
Okta Management APIs

Allows customers to easily access the Okta API

Copyright 2018 - Present Okta, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

API version: 3.0.0
Contact: devex-public@okta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package okta

import (
	"encoding/json"
)

// DomainLinks struct for DomainLinks
type DomainLinks struct {
	Certificate map[string]interface{} `json:"certificate,omitempty"`
	Self map[string]interface{} `json:"self,omitempty"`
	Verify map[string]interface{} `json:"verify,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DomainLinks DomainLinks

// NewDomainLinks instantiates a new DomainLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainLinks() *DomainLinks {
	this := DomainLinks{}
	return &this
}

// NewDomainLinksWithDefaults instantiates a new DomainLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainLinksWithDefaults() *DomainLinks {
	this := DomainLinks{}
	return &this
}

// GetCertificate returns the Certificate field value if set, zero value otherwise.
func (o *DomainLinks) GetCertificate() map[string]interface{} {
	if o == nil || o.Certificate == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainLinks) GetCertificateOk() (map[string]interface{}, bool) {
	if o == nil || o.Certificate == nil {
		return nil, false
	}
	return o.Certificate, true
}

// HasCertificate returns a boolean if a field has been set.
func (o *DomainLinks) HasCertificate() bool {
	if o != nil && o.Certificate != nil {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given map[string]interface{} and assigns it to the Certificate field.
func (o *DomainLinks) SetCertificate(v map[string]interface{}) {
	o.Certificate = v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *DomainLinks) GetSelf() map[string]interface{} {
	if o == nil || o.Self == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainLinks) GetSelfOk() (map[string]interface{}, bool) {
	if o == nil || o.Self == nil {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *DomainLinks) HasSelf() bool {
	if o != nil && o.Self != nil {
		return true
	}

	return false
}

// SetSelf gets a reference to the given map[string]interface{} and assigns it to the Self field.
func (o *DomainLinks) SetSelf(v map[string]interface{}) {
	o.Self = v
}

// GetVerify returns the Verify field value if set, zero value otherwise.
func (o *DomainLinks) GetVerify() map[string]interface{} {
	if o == nil || o.Verify == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Verify
}

// GetVerifyOk returns a tuple with the Verify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainLinks) GetVerifyOk() (map[string]interface{}, bool) {
	if o == nil || o.Verify == nil {
		return nil, false
	}
	return o.Verify, true
}

// HasVerify returns a boolean if a field has been set.
func (o *DomainLinks) HasVerify() bool {
	if o != nil && o.Verify != nil {
		return true
	}

	return false
}

// SetVerify gets a reference to the given map[string]interface{} and assigns it to the Verify field.
func (o *DomainLinks) SetVerify(v map[string]interface{}) {
	o.Verify = v
}

func (o DomainLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Certificate != nil {
		toSerialize["certificate"] = o.Certificate
	}
	if o.Self != nil {
		toSerialize["self"] = o.Self
	}
	if o.Verify != nil {
		toSerialize["verify"] = o.Verify
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *DomainLinks) UnmarshalJSON(bytes []byte) (err error) {
	varDomainLinks := _DomainLinks{}

	err = json.Unmarshal(bytes, &varDomainLinks)
	if err == nil {
		*o = DomainLinks(varDomainLinks)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &additionalProperties)
	if err == nil {
		delete(additionalProperties, "certificate")
		delete(additionalProperties, "self")
		delete(additionalProperties, "verify")
		o.AdditionalProperties = additionalProperties
	} else {
		return err
	}

	return err
}

type NullableDomainLinks struct {
	value *DomainLinks
	isSet bool
}

func (v NullableDomainLinks) Get() *DomainLinks {
	return v.value
}

func (v *NullableDomainLinks) Set(val *DomainLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainLinks(val *DomainLinks) *NullableDomainLinks {
	return &NullableDomainLinks{value: val, isSet: true}
}

func (v NullableDomainLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

